/** Field definitions for the generic admin CRUD screens. */
export const ADMIN_ENTITIES = {
  universities: {
    label: "Universities",
    icon: "Building2",
    titleField: "name",
    columns: ["name", "short_name", "slug", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "short_name", label: "Short name" },
      { name: "slug", label: "Slug", hint: "Auto-generated from the name if left blank" },
      { name: "state_id", label: "State", type: "ref", ref: "states" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "official_website", label: "Official website" },
      { name: "official_result_url", label: "Result URL" },
      { name: "official_notice_url", label: "Notice URL" },
      { name: "banner_url", label: "Banner image URL" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  colleges: {
    label: "Colleges",
    icon: "School",
    titleField: "name",
    columns: ["name", "city", "slug", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "university_id", label: "University", type: "ref", ref: "universities", required: true },
      { name: "slug", label: "Slug" },
      { name: "city", label: "City" },
      { name: "address", label: "Address" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  courses: {
    label: "Courses",
    icon: "GraduationCap",
    titleField: "name",
    columns: ["name", "short_name", "course_type", "duration", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "university_id", label: "University", type: "ref", ref: "universities", required: true },
      { name: "short_name", label: "Short name" },
      { name: "slug", label: "Slug" },
      { name: "course_type", label: "Type", type: "select", options: ["UG", "PG", "Diploma", "Certificate"] },
      { name: "duration", label: "Duration", hint: "e.g. 3 Years" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  subjects: {
    label: "Subjects",
    icon: "BookOpen",
    titleField: "name",
    columns: ["name", "code", "semester_or_year", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "course_id", label: "Course", type: "ref", ref: "courses", required: true },
      { name: "code", label: "Subject code" },
      { name: "semester_or_year", label: "Semester / Year", hint: "e.g. Semester 1" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  categories: {
    label: "Categories",
    icon: "Tags",
    titleField: "name",
    columns: ["name", "slug", "icon", "status"],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "slug", label: "Slug" },
      { name: "icon", label: "Lucide icon name", hint: "e.g. FileText, NotebookPen" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  exam_schedules: {
    label: "Exam Schedules",
    icon: "CalendarClock",
    titleField: "semester",
    columns: ["semester", "exam_type", "session", "start_date", "end_date", "status"],
    fields: [
      { name: "course_id", label: "Course", type: "ref", ref: "courses", required: true },
      { name: "semester", label: "Semester / Year", required: true, hint: "Must match the student's semester exactly, e.g. Semester 3" },
      { name: "exam_type", label: "Exam type", type: "select", options: ["Main", "Supplementary", "Practical", "Internal"] },
      { name: "session", label: "Session", hint: "e.g. 2025-26" },
      { name: "start_date", label: "Start date", required: true, hint: "YYYY-MM-DD" },
      { name: "end_date", label: "End date", hint: "YYYY-MM-DD" },
      { name: "subject_wise_dates", label: "Subject-wise dates", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  resources: {
    label: "Resources",
    icon: "FileText",
    titleField: "title",
    columns: ["title", "year", "file_type", "is_verified", "status"],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "university_id", label: "University", type: "ref", ref: "universities" },
      { name: "course_id", label: "Course", type: "ref", ref: "courses" },
      { name: "subject_id", label: "Subject", type: "ref", ref: "subjects" },
      { name: "category_id", label: "Category", type: "ref", ref: "categories" },
      { name: "slug", label: "Slug" },
      { name: "year", label: "Year", type: "number" },
      { name: "file_type", label: "File type", type: "select", options: ["pdf", "doc", "ppt", "image"] },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_verified", label: "Verified", type: "boolean" },
      { name: "is_premium", label: "Premium", type: "boolean" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    note: "File uploads arrive in a later step — these records describe the resource only.",
  },
  syllabus: {
    label: "Syllabus",
    icon: "BookOpenCheck",
    titleField: "title",
    columns: ["title", "semester_or_year", "year", "file_type", "status"],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "university_id", label: "University", type: "ref", ref: "universities", required: true },
      { name: "course_id", label: "Course", type: "ref", ref: "courses", required: true },
      { name: "subject_id", label: "Subject", type: "ref", ref: "subjects" },
      { name: "semester_or_year", label: "Semester / Year", hint: "e.g. Semester 3" },
      { name: "year", label: "Academic year", type: "number" },
      { name: "slug", label: "Slug" },
      { name: "file_url", label: "File URL" },
      { name: "preview_url", label: "Preview URL" },
      { name: "thumbnail_url", label: "Thumbnail URL" },
      { name: "file_type", label: "File type", type: "select", options: ["pdf", "doc", "image", "video"] },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_verified", label: "Verified", type: "boolean" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    note: "Add syllabus files and linked study plans for each course and subject.",
  },
};

export const ADMIN_NAV = [
  { to: "/admin", label: "Overview", icon: "LayoutDashboard" },
  { to: "/admin/pdfs", label: "PDF Approval", icon: "FileCheck2" },
  ...Object.entries(ADMIN_ENTITIES).map(([key, cfg]) => ({
    to: `/admin/${key}`,
    label: cfg.label,
    icon: cfg.icon,
  })),
  { to: "/admin/users", label: "Users & Roles", icon: "Users" },
];

export const ROLES = ["student", "contributor", "moderator", "admin"];
